import Head from 'next/head'
import { StrictMode } from 'react'
import MainSection from '../components/Section/MainSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StrictMode>
        <MainSection />
      </StrictMode>
    </div>
  )
}
