import { NextPage } from "next";
import Head from "next/head";
import MainSection from "../components/Section/MainSection";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <MainSection />
      </div>
    </div>
  );
};

export default Home;
